export const ActionTypes = {
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',
  CONFIRM_SIGN_UP_SUCCESS: 'CONFIRM_SIGN_UP_SUCCESS',
  CONFIRM_SIGN_UP_ERROR: 'CONFIRM_SIGN_UP_ERROR',
  LOADING_IN_PROGRESS: 'LOADING_IN_PROGRESS',
  LOADING_COMPLETE: 'LOADING_COMPLETE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOG_OUT: 'LOG_OUT',
  IS_AUTHENTICATED: 'IS_AUTHENTICATED',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILED: 'UPDATE_PROFILE_FAILED',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILED: 'GET_PROFILE_FAILED'
};
